default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost       # Nếu Rails chạy trên máy host
  username: rails_user
  password: secret
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spree_development

test:
  <<: *default
  database: spree_test

production:
  <<: *default
  database: spree_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
